### ISSUE TITLE
can not build esp32 s3 box-3

### ISSUE THREAD

**Issue by lecrams** [esphome/firmware#198]
using esphome 2024.5.4 gives me errors when I try to build the box-3 yaml:
ERROR Unable to import component image:
Traceback (most recent call last):
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\loader.py", line 176, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\components\image\__init__.py", line 10, in <module>
    from magic import Magic
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

What can be wrong?

**Comment by lecrams** [comment]
Solved the issue by installing libmagic with the following commands:
pip install python-libmagic
pip install python-magic-bin.
Now everything builds fine
