### ISSUE TITLE
Unable to compile voice-assistant for RaspiAudio Muse Luxe

### ISSUE THREAD

**Issue by mroxso** [esphome/firmware#287]
I got a problem while updating my RaspiAudio Muse Luxe to the latest version.

Currently installed version:  2024.10.2 
Latest version:  2024.12.1 

```
INFO ESPHome 2024.12.1
INFO Reading configuration /config/esphome/raspiaudio-muse-luxe-424368.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/3552/head
INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING `attenuation: 11db` is deprecated, use `attenuation: 12db` instead
WARNING GPIO12 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Updating https://github.com/espressif/esp-adf@v2.5
INFO Updating submodules (components/esp-sr, components/esp-adf-libs) for https://github.com/espressif/esp-adf@v2.5
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 503, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 213, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 231, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 341, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 307, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 811, in copy_files
    shutil.copytree(
  File "/usr/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/data/idf_components/b0ad5728/components/esp-sr/docs/myapp/bin/python', '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/bin/python', "[Errno 17] File exists: 'python3' -> '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/bin/python'"), ('/data/idf_components/b0ad5728/components/esp-sr/docs/myapp/bin/python3', '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/bin/python3', "[Errno 17] File exists: '/usr/bin/python3' -> '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/bin/python3'"), ('/data/idf_components/b0ad5728/components/esp-sr/docs/myapp/lib64', '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/lib64', "[Errno 17] File exists: 'lib' -> '/data/build/raspiaudio-muse-luxe-424368/components/esp-sr/docs/myapp/lib64'")]
```

My ESPHome Config File for this devices looks like this (keys removed):
```
substitutions:
  name: raspiaudio-muse-luxe-XXXX
  friendly_name: RaspiAudio Muse Luxe XXXX
packages:
  raspiaudio.muse-luxe-voice-assistant: github://esphome/firmware/voice-assistant/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: XXXXX


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Comment by mroxso** [comment]
I was able to get the workaround working from #286 also for the RaspiAudio Muse Luxe by slightly changing the workaround.

The following has to be added to the ESPHome Config of the RaspiAudio Muse Luxe:
```
esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
```

The final config could look like this:
```
substitutions:
  name: raspiaudio-muse-luxe-XXXXX
  friendly_name: RaspiAudio Muse Luxe XXXXX
packages:
  raspiaudio.muse-luxe-voice-assistant: github://esphome/firmware/voice-assistant/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: XXXXX


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
```

**Please note: This is only a workaround.**
